
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.4
    hooks:
      # Run the linter.
      - id: ruff
      # Run the linter for import sorting.
      - id: ruff
        args: ["check", "--select", "I", "--fix"]
      # Run the formatter.
      - id: ruff-format